.travis.yml
1. Add "build" and "npm i" action for both client and lite-app.
2. Use different compression for windows files.
3. Have run this script on local machine and it works.
=> Modify the yml file of travis CI.

build.sh
1. in build.sh, add "." at the source directory of copy command.
=> Modify build.sh

package.json, yarn.lock
```
// $ npm i yarn -g
$ yarn upgrade mcs-lite-introduction
```
https://github.com/MCS-Lite/mcs-lite/blob/master/CHANGELOG.md#released-2017-06-02
=> chore(mcs-lite-introduction): upgrade to 0.2.4

client/app/components/header/configs/resources.js
Update the links and wording on header.
=> fix(header): update resource related links.

client/en.po, client/zh-CN.po, client/zh-TW.po
add *.po translation file for en, tw and cn
=> feat(i18N): add en, zh-TW, zh-CN translation for webpages.

client/en.po, client/zh-CN.po, client/zh-TW.po
=> feat(i18N): add translation for new string.

client/en.po
=> fix(i18N): English format.

client/package.json
remove babel and add babel-cli
=> fix(client): update package.json

.travis.yml, build.sh
1. Remove linux nwjs package in build.sh
2. Duplicate a node package for linux
=> remove linux package and use node instead.

client/apiHints/5/2/retrieve/javascript.ejs, client/mcs-layout.pot
=> fix(apihint): add datachannel ID for string.

adminServer/controllers/users.js, adminServer/routers/index.js
1. Modify the string parser to URL-encoded form.
2. FE only needs to read csv file and attach it in the request body and use 'text/csv' in content-type.
3. There is no change needed in BE. Still parse the content in key-value format.
=> bugfix(admin): content-type issue for upload csv.

adminServer/controllers/users.js
update the new line characters for upload user list in csv format.
=> bugfix(admin): parse the new line with both /r and /n.

mysql/utils.js
* [ __FIX__ ] Skip insertion when no data in NeDB database.
=> fix(migration/mysql): skip insertion when no data

wotserver/lib/websocket-broker.js
* [ __FIX__ ]: websocket server crashed on push datapoints.
=> fix(websocket): remove unused file reference

package.json, yarn.lock
* [ __CHORE__ ] Add bluebird to dependencies
=> chore(package): add bluebird to dependencies

adminServer/controllers/users.js, mysql/users/index.js, nedb/users/index.js, package.json, yarn.lock
* [ __FIX__ ] Response error message when csv format error / email has been registered.
=> fix(admin/user): response error message when csv format error

adminServer/controllers/service.js, adminServer/controllers/users.js, adminServer/routers/index.js, mysql/datachannels/index.js, mysql/datapoints/index.js, mysql/devices/index.js, mysql/prototypes/index.js, mysql/unittypes/index.js, mysql/users/index.js, nedb/datachannels/index.js, nedb/datapoints/index.js, nedb/devices/index.js, nedb/prototypes/index.js, nedb/unittypes/index.js, nedb/users/index.js, restserver/controllers/unittypes.js
* [ __FIX__ ] Clear all data under NeDB
* [ __ADD__ ] Clear all data under MySQL
* [ __FIX__ ]  Unittypes query always return empty array
=> fix(admin): clear all data api

client/app/components/dataChannelCards/common/wrapper/index.js, client/app/components/prototypeDetail/dataChannelContent/index.js
=> fix(Prototype/DataChannel): display datachannelId instead of updateAt

adminServer/controllers/service.js, index.js, package.json, yarn.lock
* [ __FIX__ ] Random crashes on restart lite server
=> fix(app): random crashes on restart lite server

adminServer/controllers/users.js, adminServer/routers/index.js
- [ __ADD__ ] User email available check API
=> feature(Users): user email available check API

adminServer/controllers/users.js, mysql/users/index.js
Admin server api `/users` returns all user list when url query is empty.
=> fix(admin/user): retrieve user list with mysql

package.json, restserver/index.js, yarn.lock
=> Remove stream server

adminServer/controllers/service.js, adminServer/controllers/users.js, index.js
* [ __FIX__ ] Port binding failure on restart server
=> fix(server): port binding failure on restart server

client/app/components/dataChannelCards/common/wrapper/index.js, client/app/components/deviceDetail/dataChannelContent/index.js, mysql/datachannels/schema.js, nedb/datachannels/schema.js, restserver/controllers/datachannels.js
* Add hasHistory entry for datachannels
=>  fix(datachannels): add hasHistory entry for datachannels

restserver/controllers/generator.js
fix(APIHint): show correct WebSocket server port in example code
=> fix(APIHint): show correct WebSocket server port in example code
